############################################################################
######################         server-zipkin         #######################
############################################################################
spring:
  application:
    name: server-zipkin

server:
  port: 8770
 
      

