eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zzyZuul
zuul:
  routes:
    api-a:
      path: /a/**  #以/a/ 开头的请求都转发给ribbon服务
      serviceId: zzyRibbon
    api-b:
      path: /b/**
      serviceId: zzyFeign
  host: #zuul部署上物理机之后，如果使用默认配置，请求很容易超时
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  config: /Users/zhaozhengyang/Documents/work/x9/git/Zzy/src/main/resources/log4j.xml