eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zzyZuul
zuul:
  routes:
    api-a:
      path: /a/**  #以/a/ 开头的请求都转发给ribbon服务
      serviceId: zzyRibbon
    api-b:
      path: /b/**
      serviceId: zzyFeign