server:
  port: 8767
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/351588469/zzySpringCloudConfig/
          #配置仓库路径
          searchPaths: respo
          #如果Git仓库为公开仓库，可以不填写用户名和密码
          username: 351588469
          password: zhengyang940830
      #配置仓库的分支
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
